export const SearchFieldWordList = [
  'Copywriter',
  'Gymshark',
  'Content Creator',
  'Ridge',
  'Frontend Developer',
  'Skims',
  'Product Manager',
  'The Oodie',
  'Paid Media Specialist',
  'Glossier',
  'Growth Marketer',
  'UGC Content Creator',
  'Quip',
  'Tiktok Content Creator',
  'Retail Associate',
  'Cometeer',
  'Google Ads Specialist',
  'Harrys',
  'Facebook Ads Specialist',
  'Capser',
  'CRO Specialist',
  'Data Scientist',
  'SEO Executive',
  'Allbirds',
  'VP of Brand',
  'Account Executive',
  'Sales Associate',
  'Senior Software Engineer',
];
